name: Dependency Review

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3

      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.1

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          allow-licenses: AGPL-3.0-or-later

          fail-on-severity: low
          license-check: true
          vulnerability-check: true
