name: GitHub Release CI/CD

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runs-on.os }}
    name: build (${{ matrix.runs-on.os }}, ${{ matrix.build.profile }})
    timeout-minutes: 5
    strategy:
      matrix:
        runs-on:
          - os: ubuntu-latest
            binary_ext: ""

          - os: windows-latest
            binary_ext: .exe

        build:
          - profile: release
            cargo_args: --release

    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v6

      - name: 🏗 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606

      - name: 🏗️ Build (${{ matrix.runs-on.os }} / ${{ matrix.build.profile }})
        run: cargo build ${{ matrix.build.cargo_args }}

      - name: 📦 Upload artifact (${{ matrix.runs-on.os }} / ${{ matrix.build.profile }})
        uses: actions/upload-artifact@v7
        with:
          path: target/${{ matrix.build.profile }}/pdup-rs${{ matrix.runs-on.binary_ext }}
          if-no-files-found: error
          retention-days: 7
          archive: false

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    permissions:
      contents: write
    steps:
      - name: 📦 Download artifact
        uses: actions/download-artifact@v8
        id: download
        with:
          pattern: "pdup-rs*"
          merge-multiple: true

      - name: 📦 Create GitHub Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          fail_on_unmatched_files: true
          preserve_order: true
          generate_release_notes: true
          files: |
            pdup-rs
            pdup-rs.exe
